<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="description" content="This repo stores in static files notes taken since the 1990s. I started taking notes in Microsoft Access, then I built an ASP site over SQL server, then I built a PHP site over SQLite, then I built an Angular JS site over Azure Storage BLOBs." />
        <meta name="robots" content="index, follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <base href="/" />

        <link rel="canonical" href="http://the-funky-knowledge-base.github.io/" />
        <link rel="icon" type="image/x-icon" href="./images/favicon.ico" />
        <link rel="stylesheet" href="./index.min.css" />
        <script src="./index.min.js"></script>

        <title>Catching Exceptions from System.ComponentModel.BackgroundWorker; DispatcherUnhandledException Fails to Fire for Background Threads - the funky knowledge base</title>
    </head>

    <body class="mdc-typography">
        <h1>the funky knowledge base</h1>
        <h2>personal notes from way, _way_ back and maybe today</h2>
        <main>
<section class="entry">
    <h3>Catching Exceptions from System.ComponentModel.BackgroundWorker; DispatcherUnhandledException Fails to Fire for Background Threads</h3>

<pre>
<p>The details of this problem is introduced in “Catch DispatcherUnhandledException from other Thread” here:</p>
<pre><code>http://forums.microsoft.com/msdn/showpost.aspx?postid=1164067&amp;siteid=1
</code></pre>
<p>Chango V. of Microsoft answers this issue with this pattern:</p>
<p>(i) Make the Dispatcher object of the main thread available to your worker thread. (You could either pass it as a parameter to the thread start method or just use Application.Current.Dispatcher.)</p>
<p>(ii) Use a try-catch-finally in the worker thread. (In general, the catch block should immediately rethrow critical exceptions: OutOfMemoryException, SecurityException, SEHException, maybe also NullReferenceException.)</p>
<p>(iii) The [worker-thread] catch block calls mainDispatcher.Invoke(DispatcherPriority.Send, ExceptionCallback, exception).</p>
<p>(iv) ExceptionCallback() throws the exception object passed to it. This happens on the main thread, so handlers added to Application.DispatcherUnhandledException will be invoked and can “handle” the exception.</p>
<p>(v) If your worker thread resumes execution, the exception was “handled.”</p>
<p>The following is a worker-thread catch block following this pattern in a WPF application:</p>
<pre><code>catch ( Exception ex )
{
    Dispatcher d = ClientApplication.Current.Dispatcher;
    ClientApplication.WorkerThreadExceptionCallback delg =
        ClientApplication.WorkerThreadException;
    d.Invoke( DispatcherPriority.Send, delg, ex );

}
</code></pre>
<p>The main thread defines:</p>
<pre><code>internal static void
    WorkerThreadException( Exception WorkerThreadException )
{
    throw WorkerThreadException as Exception;
}

internal delegate void
    WorkerThreadExceptionCallback( Exception WorkerThreadException );
</code></pre>

</pre>

    <span class="date"> <strong>mod date:</strong> 2007-10-02T18:51:34.000Z </span>
</section>

        </main>

        <footer>
            &copy; 2019 Bryan D. Wilhite
            <a href="https://twitter.com/BryanWilhite">@BryanWilhite</a>
        </footer>
    </body>

</html>